
# TODO: organizar diretório (Package) do projeto e incluir/remover pastas necessárias
# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - capios/R.generated.swift
  - ".*Test\\.swift"

# only correctables for now
whitelist_rules:

  # default:  
  - colon # 4571 warnings/errors + run auto correct  + run success  Enable       
  - comma #1610 errors + run auto correct + run success Enable
  - trailing_comma # no errors Enable
  - statement_position  # 808 warnings/errors + run auto correct + Enable
  - modifier_order #869 warnings/errors +run auto correct + run success OK
  - empty_enum_arguments # 63 errors + run auto correct + run success Enable
  - empty_parameters # 29 errors + run auto correct + run success Enable
  - empty_parentheses_with_trailing_closure # 52 errors + run auto correct + run success Enable
  - leading_whitespace  # 17 errors + run auto correct+ run success Enable
  - legacy_cggeometry_functions # no errors Enable
  - legacy_constant # 6 errors + run auto correct + run success Enable
  - legacy_constructor #37 errors + run auto correct + Enable
  - legacy_nsgeometry_functions # no errors + run auto correct + run success Enable
  - protocol_property_accessors_order # 2 errors + run auto correct + run success  Enable
  - redundant_discardable_let # 2 errors + run auto correct + run success Enable
  - redundant_objc_attribute # no errors Enable
  - redundant_optional_initialization #239 error + run auto correct + run success Enable
  - redundant_void_return #  8 errors + run auto correct  +  run success  Enable
  - return_arrow_whitespace # 31 errors + run auto correct + Enable
  - trailing_semicolon #97 errors + run auto correct + run success Enable 
  - unneeded_parentheses_in_closure_argument #305 errors + run auto correct +  run success  OK
  - operator_usage_whitespace # 727 errors + run auto correct + run success   OK
  - mark # 304 errors + auto correct + run success + Enable
  - trailing_newline #Enable Run Test 322 errors + run auto correct + run success(apos retirar arquivos que sao alterados pelo rx)
  - unused_control_flow_label # no errors + run auto correct + run success Enable
  - void_return # 95 errors + run auto correct + run success Enable
  - weak_computed_property # no errors + run auto correct + run success Enable
  - unused_closure_parameter # 268 errors + run  auto correct + run success(after solve 2 errors)  Enabled
  - vertical_whitespace_between_cases # +999 errors + run auto correct + run success Evalute
  - unused_import # no errors + run auto correct + run success N
  - vertical_whitespace_closing_braces # +999 warnings/errors + run auto correct + run success Evalute
  - vertical_whitespace_opening_braces # 2606 warnings/erros + run auto correct + run success Evalute
  - vertical_whitespace # +999 errors + run auto correct + run success Teste max 2 linhas
  #- custom_rules
  #- force_unwrapping

# configurations
vertical_whitespace_between_cases:
  severity: error

vertical_whitespace_opening_braces:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

modifier_order:
  severity: error

statement_position:
  severity: error

trailing_comma:
  severity: error  

colon:
  severity: error  

vertical_whitespace:
  max_empty_lines: 2
  severity: error  

comma: error
empty_enum_arguments: error
empty_parameters: error
empty_parentheses_with_trailing_closure: error
leading_whitespace: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
mark: error
legacy_nsgeometry_functions: error
operator_usage_whitespace: error
protocol_property_accessors_order: error
redundant_discardable_let: error
redundant_objc_attribute: error
redundant_optional_initialization: error
redundant_void_return: error
return_arrow_whitespace: error
trailing_newline: error
trailing_semicolon: error
unneeded_parentheses_in_closure_argument: error
unused_closure_parameter: error
unused_control_flow_label: error
unused_import: error
void_return: error
weak_computed_property: error

force_unwrapping: error
force_cast: error
# Use "xcode" so that when you build, the result will be shown in Xcode
reporter: "xcode"

# custom_rules:
#   no_string_allowed: # rule identifier
#     name: "Boas Praticas - 2D" # rule name. optional.
#     regex: "[=,= ]\".*\"$|\"(.*)\"" # matching pattern
#     match_kinds: string
#     message: "Criar todas as strings necessárias, nos arquivos de internacionalização \".strings\" do \"Next-Assets\"." # violation message. optional.
#     severity: error # violation severity. optional.

#   no_print_allowed: # rule identifier
#     name: "Boas Praticas - 5E" # rule name. optional.
#     regex: "print((.*))" # matching pattern
#     message: "Prints poluem o console e dificultam debugs. Antes de fazer o PR, remover prints." # violation message. optional.
#     severity: warning # violation severity. optional.
  
#   no_comments_allowed: # rule identifier
#     name: "Boas Praticas - 5J" # rule name. optional.
#     regex: "\/\/" # matching pattern
#     message: "Códigos comentados que não serão mais utilizados, devem ser removidos do projeto a fins de CleanCode" # violation message. optional.
#     severity: warning # violation severity. optional.
  
#   weak_self_on_closures: # rule identifier
#     name: "Teste Closures" # rule name. optional.
#     regex: "{(.*)}" # matching pattern
#     match_kinds: string
#     message: "Criar todas as strings necessárias, nos arquivos de internacionalização \".strings\" do \"Next-Assets\"." # violation message. optional.
#     severity: error # violation severity. optional.


# Disable default
  #closure_end_indentation: error
  #closure_spacing: error
  #- closing_brace #no errors found N
  #- closure_end_indentation #348 erros + run autocorrect + run success - 1 correctable error N
  #- closure_spacing N
  #- explicit_init N
  #- explicit_self N
  #- implicit_return N
  #- joined_default_parameter N
  #- literal_expression_end_indentation N
  #- nimble_operator N
  #- number_separator N
  #- opening_brace #Enable 
  #- redundant_nil_coalescing N
  #- redundant_type_annotation N
  #- sorted_imports  N
  #- trailing_whitespace #Enable 11656 warnings/errors + run auto correct + 
  #- untyped_error_in_catch #8 errors + run auto correct + run 2 errors N
  #- private_over_fileprivate #remove